name: micro_app_about
description: A new Flutter package project.
version: 0.0.1
author:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  micro_core:
    path: ../micro_core
  micro_commons_deps:
    path: ../micro_commons_deps

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
