name: micro_core
description: A new Flutter package project.
version: 0.0.1
author:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  micro_commons_deps:
    path: ../micro_commons_deps

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.2.2
  build_runner: ^1.12.2
  mockito: ^5.0.5
  

flutter:
