name: micro_commons_deps
description: A new Flutter package project.
version: 0.0.1
author:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.0 
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.0
  flutter_modular: ^3.1.1
  mobx: ^2.0.1
 
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.5

flutter:
